### ISSUE TITLE
os-audit vs. gVisor

### ISSUE THREAD

**Issue by Capstan** [GoogleCloudPlatform/k8s-node-tools#11]
https://cloud.google.com/kubernetes-engine/docs/how-to/sandbox-pods#regular-pod

IIUC, in order to have the audit logging mechanism work when also using the GKE Sandbox is to add an additional toleration:

```
tolerations:
  - effect: NoSchedule
    key: sandbox.gke.io/runtime
    operator: Equal
    value: gvisor
```

Otherwise, the DaemonSet will not schedule the audit logging pods on the gVisor nodes, and we lose visibility on what happens there.
